### ISSUE TITLE
Compat report shows false positives

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/vscode-theia-comparator#16]
See for example the name space "authentication" shows two missing variants of "getSession" (https://eclipse-theia.github.io/vscode-theia-comparator/filtered-status.html). However, they seemed to be implemented: https://github.com/eclipse-theia/theia/blob/master/packages/plugin/src/theia.d.ts#L11342

**Comment by JonasHelming** [comment]
@lucas-koehler

**Comment by lucas-koehler** [comment]
@JonasHelming I investigated this and it turns out 2 of the 3 `getSession` methods are not shown as implemented because the method signature does slightly vary between VSCode and Theia. In VSCode the second parameter is `scopes: readonly string[]` for all three methods. In Theia this is only the case for one of the methods. This is the one being shown as implemented. The other two have `scopes: string[]` as their second parameter.
This is not recognized by the comparator as the same signature because it uses hashing over the parameter types and `readonly` is part of the type.

To fix the report it would be enough to simply adjust the signatures in Theia.

**Comment by lucas-koehler** [comment]
The two `getSession` methods should be shown as implemented after https://github.com/eclipse-theia/theia/pull/10837 is merged.
